name: Process Issue with AI

on:
  issues:
    types: [opened]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
      - name: Install dependencies
        run: |
          source $HOME/.cargo/env
          uv sync --extra test
      
      - name: Process Issue
        run: |
          source $HOME/.cargo/env
          # Use the current development branch instead of main
          CURRENT_BRANCH="${{ github.head_ref || github.ref_name }}"
          echo "Processing issue against branch: $CURRENT_BRANCH"
          uv run python -m sip process-issue ${{ github.event.issue.number }} --branch "$CURRENT_BRANCH"
        env:
          AGENT_GITHUB_TOKEN: ${{ secrets.AGENT_GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}